<?php
/**
 * Created by PhpStorm.
 * Author: 紫云沫雪こ
 * Email:email1946367301@163.com
 * Date: 2019/5/17 0017
 * Time: 14:39
 */

namespace Future\Admin\Form\Field;


use Future\Admin\Form\Field;

class Image extends Field
{
    protected $view = <<<EOF
   <input  type="text" size="50" <%elementAttribute%> data-base64="<%data-base64%>" ><%extend%>  
EOF;

    public function __construct($form)
    {
        $this->form = $form;
    }

    public function render()
    {
        $Choose = lang('Choose');
        $Upload = lang('Upload');
        $base64 = '';
        if ($this->elementOption['value']) {
            $base64 = get_upload_image($this->elementOption['value']);
        }
        $extend     = " <span><button type=\"button\" id=\"plupload-{$this->column}\"  class=\"btn btn-danger plupload\" data-input-id=\"c-{$this->column}\" data-mimetype=\"image/*\"
                    data-multiple=\"false\" data-preview-id=\"p-{$this->column}\"><i  class=\"fa fa-upload\"></i> {$Upload}</button></span> <span><button type=\"button\" id=\"fachoose-{$this->column}\"
                    class=\"btn btn-primary fachoose\" data-input-id=\"c-{$this->column}\"  data-mimetype=\"image/*\" data-multiple=\"false\"><i
                    class=\"fa fa-list\"></i>{$Choose}</button></span>  <ul class=\"row list-inline plupload-preview\" id=\"p-{$this->column}\"></ul>";
        $this->view = str_replace(['<%data-base64%>', '<%extend%>'], [$base64, $extend], $this->view);
        return parent::render(); // TODO: Change the autogenerated stub
    }
}